-- MASTER SCHEMA FOR ROSTARA
-- Run this script in Supabase SQL Editor to set up the entire database.
-- This script is safe to re-run. It will drop existing policies to ensure the latest version is applied.

-- ==========================================
-- 0. SAFE TYPE CREATION
-- ==========================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status') THEN
        create type public.order_status as enum ('pending', 'processing', 'shipped', 'delivered', 'cancelled');
    END IF;
END
$$;

-- ==========================================
-- 1. ORDERS TABLE
-- ==========================================
create table if not exists public.orders (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  full_name text not null,
  email text,
  phone text,
  address text,
  city text,
  postal_code text,
  notes text,
  total_price decimal(12,2) not null,
  items jsonb, -- Stores the cart items as JSON
  status public.order_status default 'pending'
);

-- RLS for Orders
alter table public.orders enable row level security;

-- Drop simple policies if they exist to avoid conflicts on re-run
drop policy if exists "Users can view own orders" on public.orders;
drop policy if exists "Users can create orders" on public.orders;
drop policy if exists "Admins can view all orders" on public.orders;
drop policy if exists "Admins can update orders" on public.orders;

-- Users can see their own orders
create policy "Users can view own orders" on public.orders for select using (
  auth.uid() = user_id
);

-- Users can insert their own orders
create policy "Users can create orders" on public.orders for insert with check (
  auth.uid() = user_id
);

-- Admins can view all orders (Replace 'admin@rostara.ir' with real admin emails or use a roles table)
create policy "Admins can view all orders" on public.orders for select using (
  auth.jwt() ->> 'email' in ('admin@rostara.ir', 'support@rostara.ir') 
);

-- Admins can update orders
create policy "Admins can update orders" on public.orders for update using (
  auth.jwt() ->> 'email' in ('admin@rostara.ir', 'support@rostara.ir')
);


-- ==========================================
-- 2. FORUM TABLES
-- ==========================================

-- Forum Posts
create table if not exists public.forum_posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text not null,
  user_id uuid references auth.users not null,
  user_email text, 
  category text default 'general',
  likes_count int default 0,
  comments_count int default 0
);

-- Forum Comments
create table if not exists public.forum_comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  post_id bigint references public.forum_posts not null,
  user_id uuid references auth.users not null,
  user_email text,
  content text not null
);

-- Forum Likes
create table if not exists public.forum_likes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  post_id bigint references public.forum_posts not null,
  user_id uuid references auth.users not null,
  unique(post_id, user_id)
);

-- RLS for Forum
alter table public.forum_posts enable row level security;
alter table public.forum_comments enable row level security;
alter table public.forum_likes enable row level security;

-- Drop existing Forum policies
drop policy if exists "Public posts are viewable by everyone" on public.forum_posts;
drop policy if exists "Public comments are viewable by everyone" on public.forum_comments;
drop policy if exists "Public likes are viewable by everyone" on public.forum_likes;
drop policy if exists "Star users can create posts" on public.forum_posts;
drop policy if exists "Authenticated users can comment" on public.forum_comments;
drop policy if exists "Authenticated users can like" on public.forum_likes;
drop policy if exists "Users can dislike" on public.forum_likes;

-- Policies for Forum
create policy "Public posts are viewable by everyone" on public.forum_posts for select using (true);
create policy "Public comments are viewable by everyone" on public.forum_comments for select using (true);
create policy "Public likes are viewable by everyone" on public.forum_likes for select using (true);

-- Only Star Users (users with orders) can create posts
create policy "Star users can create posts" on public.forum_posts for insert with check (
  auth.uid() in (select user_id from public.orders)
);

create policy "Authenticated users can comment" on public.forum_comments for insert with check (
  auth.role() = 'authenticated'
);

create policy "Authenticated users can like" on public.forum_likes for insert with check (
  auth.role() = 'authenticated'
);

create policy "Users can dislike" on public.forum_likes for delete using (
  auth.uid() = user_id
);

-- ==========================================
-- 3. UTILITY FUNCTIONS (Optional)
-- ==========================================
-- Function to handle like counters automatically (Trigger preferably)
-- creating a function to call via RPC if triggers aren't used:
create or replace function increment_likes(row_id bigint)
returns void as $$
begin
  update public.forum_posts
  set likes_count = likes_count + 1
  where id = row_id;
end;
$$ language plpgsql security definer;

-- Admin: Update Order Status (Bypass RLS)
-- Admin: Update Order Status (Bypass RLS)
create or replace function admin_update_order_status(
  order_id_input uuid,
  new_status text,
  admin_secret text
)
returns jsonb
language plpgsql
security definer
as $$
begin
  -- Simple security check (matches client-side hardcoded password)
  if admin_secret != 'admin@rostara' then
    raise exception 'Unauthorized access';
  end if;

  update public.orders
  set status = new_status
  where id = order_id_input;

  if not found then
    return jsonb_build_object('success', false, 'message', 'Order not found');
  end if;

  return jsonb_build_object('success', true);
end;
$$;

create or replace function decrement_likes(row_id bigint)
returns void as $$
begin
  update public.forum_posts
  set likes_count = likes_count - 1
  where id = row_id;
end;
$$ language plpgsql security definer;

-- ==========================================
-- 4. WALLET & LOYALTY SYSTEM
-- ==========================================

-- Wallets Table (One per user)
create table if not exists public.wallets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null unique,
  credit_balance decimal(12,2) default 0, -- Rewards/Cashback (Credit)
  cash_balance decimal(12,2) default 0,   -- Real Money (Cash)
  ticket_balance int default 0,
  vip_level int default 0,
  daily_clicks int default 0, -- Current cycle clicks (0-7)
  last_click_at timestamp with time zone, -- Timestamp for 24h cooldown
  claimed_rewards jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- MIGRATION: Ensure columns exist if table was already created
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'wallets' AND column_name = 'last_click_at') THEN
        ALTER TABLE public.wallets ADD COLUMN last_click_at timestamp with time zone;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'wallets' AND column_name = 'daily_clicks') THEN
        ALTER TABLE public.wallets ADD COLUMN daily_clicks int default 0;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'wallets' AND column_name = 'vip_level') THEN
        ALTER TABLE public.wallets ADD COLUMN vip_level int default 0;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'wallets' AND column_name = 'claimed_rewards') THEN
        ALTER TABLE public.wallets ADD COLUMN claimed_rewards jsonb default '[]'::jsonb;
    END IF;
END $$;

-- Wallet Transactions (History)
-- Wallet Transactions (History)
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'transaction_type') THEN
        create type public.transaction_type as enum ('cashback', 'deposit', 'withdrawal', 'convert_ticket', 'transfer_out', 'transfer_in', 'donation_reward');
    END IF;
END $$;

create table if not exists public.wallet_transactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  wallet_id bigint references public.wallets not null,
  type public.transaction_type not null,
  amount decimal(12,2) default 0, -- Monetary value involved
  ticket_amount int default 0, -- Tickets involved
  description text
);

-- Crypto Deposits (Pending Approval)
-- Crypto Deposits (Pending Approval)
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'deposit_status') THEN
        create type public.deposit_status as enum ('pending', 'approved', 'rejected');
    END IF;
END $$;

create table if not exists public.crypto_deposits (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  tx_hash text not null,
  network text not null, -- TRC20, BSC, ERC20
  amount_declared decimal(12,2), -- User claims they sent this much (in USDT/ETH)
  status public.deposit_status default 'pending',
  admin_note text
);

-- Coupons Table
create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text unique not null,
  discount_type text check (discount_type in ('percentage', 'fixed')) not null,
  value decimal(12,2) not null,
  min_order_value decimal(12,2),
  min_items_count int,
  valid_from timestamp with time zone default now(),
  valid_until timestamp with time zone,
  usage_limit int,
  used_count int default 0,
  created_at timestamp with time zone default now()
);

-- RLS for Coupons
alter table public.coupons enable row level security;
drop policy if exists "Admins can manage coupons" on public.coupons;
drop policy if exists "Users can read valid coupons" on public.coupons; -- Optional, or keep it strict
create policy "Admins can manage coupons" on public.coupons for all using (auth.jwt() ->> 'email' in ('admin@rostara.ir', 'support@rostara.ir'));
-- We might not want users to list all coupons, just validate specific ones via RPC. So no select policy for public.

-- RLS for Wallet
alter table public.wallets enable row level security;
alter table public.wallet_transactions enable row level security;
alter table public.crypto_deposits enable row level security;

-- Policies
-- Drop Wallet Policies
drop policy if exists "Users can view own wallet" on public.wallets;
drop policy if exists "Users can view own transactions" on public.wallet_transactions;
drop policy if exists "Users can view own deposits" on public.crypto_deposits;
drop policy if exists "Users can create deposits" on public.crypto_deposits;

create policy "Users can view own wallet" on public.wallets for select using (auth.uid() = user_id);
create policy "Users can view own transactions" on public.wallet_transactions for select using (wallet_id in (select id from public.wallets where user_id = auth.uid()));
create policy "Users can view own deposits" on public.crypto_deposits for select using (auth.uid() = user_id);
create policy "Users can create deposits" on public.crypto_deposits for insert with check (auth.uid() = user_id);

-- Admin Policies
drop policy if exists "Admins can view all wallets" on public.wallets;
drop policy if exists "Admins can update wallets" on public.wallets;
drop policy if exists "Admins can view all transactions" on public.wallet_transactions;
drop policy if exists "Admins can view all deposits" on public.crypto_deposits;
drop policy if exists "Admins can update deposits" on public.crypto_deposits;

create policy "Admins can view all wallets" on public.wallets for select using (auth.jwt() ->> 'email' in ('admin@rostara.ir', 'support@rostara.ir'));
create policy "Admins can update wallets" on public.wallets for update using (auth.jwt() ->> 'email' in ('admin@rostara.ir', 'support@rostara.ir'));
create policy "Admins can view all transactions" on public.wallet_transactions for select using (auth.jwt() ->> 'email' in ('admin@rostara.ir', 'support@rostara.ir'));
create policy "Admins can view all deposits" on public.crypto_deposits for select using (auth.jwt() ->> 'email' in ('admin@rostara.ir', 'support@rostara.ir'));
create policy "Admins can update deposits" on public.crypto_deposits for update using (auth.jwt() ->> 'email' in ('admin@rostara.ir', 'support@rostara.ir'));

-- Functions

-- 1. Ensure Wallet Exists (Trigger on User Signup)
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.wallets (user_id) values (new.id);
  return new;
end;
$$ language plpgsql security definer;

-- Note: We need to recreate the trigger if it doesn't exist, but 'create trigger if not exists' is PG13+.
-- We'll use a safe block.
do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'on_auth_user_created') then
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute procedure public.handle_new_user();
  end if;
end
$$;

-- 2. Process Cashback (12% of Order)
create or replace function process_cashback(order_id_input uuid)
returns void as $$
declare
  v_user_id uuid;
  v_total decimal;
  v_cashback decimal;
  v_wallet_id bigint;
begin
  select user_id, total_price into v_user_id, v_total from public.orders where id = order_id_input;
  
  if v_user_id is null then raise exception 'Order not found'; end if;

  v_cashback := v_total * 0.12;
  
  select id into v_wallet_id from public.wallets where user_id = v_user_id;
  if v_wallet_id is null then
     insert into public.wallets (user_id) values (v_user_id) returning id into v_wallet_id;
  end if;

  update public.wallets
  set credit_balance = credit_balance + v_cashback
  where id = v_wallet_id;

  insert into public.wallet_transactions (wallet_id, type, amount, description)
  values (v_wallet_id, 'cashback', v_cashback, '12% Cashback for Order ' || order_id_input);
end;
$$ language plpgsql security definer;

-- 2.5 Delete Own Account (GDPR/Right to be erased + Rest functionality)
create or replace function delete_own_account()
returns void as $$
declare
  uid uuid;
  wallet_id_val bigint;
begin
  uid := auth.uid();
  if uid is null then raise exception 'Not authenticated'; end if;

  -- Get wallet id
  select id into wallet_id_val from public.wallets where user_id = uid;

  -- 1. Delete dependent data manually (in case cascade is missing)
  delete from public.wallet_transactions where wallet_id = wallet_id_val;
  delete from public.crypto_deposits where user_id = uid;
  delete from public.forum_likes where user_id = uid;
  delete from public.forum_comments where user_id = uid;
  delete from public.forum_posts where user_id = uid;
  delete from public.orders where user_id = uid; -- Deletes order history
  delete from public.wallets where user_id = uid; -- Deletes wallet/credits

  -- 2. Delete user from Auth (Requires security definer)
  -- Note: Depending on Supabase settings, deleting from auth.users might only be allowed via Service Role.
  -- This function is security definer, so it runs with the privileges of the creator (postgres/admin).
  delete from auth.users where id = uid;
end;
$$ language plpgsql security definer;

-- 3. Convert Credit to Ticket (500k = 1 Ticket)
create or replace function convert_credit_to_ticket()
returns void as $$
declare
  v_wallet_id bigint;
  v_credit decimal;
  v_cost decimal := 500000;
  v_tickets_to_buy int := 1; -- Currently only 1 at a time for simplicity
begin
  -- Get Wallet
  select id, credit_balance into v_wallet_id, v_credit from public.wallets where user_id = auth.uid();
  
  if v_credit < v_cost then raise exception 'Insufficient credit balance'; end if;

  -- Deduct Credit, Add Ticket
  update public.wallets 
  set credit_balance = credit_balance - v_cost,
      ticket_balance = ticket_balance + 1
  where id = v_wallet_id;

  -- Record Transaction
  insert into public.wallet_transactions (wallet_id, type, amount, ticket_amount, description)
  values (v_wallet_id, 'convert_ticket', -v_cost, 1, 'خرید تیکت جشنواره');
end;
$$ language plpgsql security definer;

-- 4. Transfer Ticket (With 50% Donation Cashback Logic)
create or replace function transfer_ticket(receiver_email text)
returns void as $$
declare
  v_sender_wallet_id bigint;
  v_receiver_wallet_id bigint;
  v_receiver_user_id uuid;
  v_sender_tickets int;
  is_donation boolean := false;
  v_donation_reward decimal := 250000; -- 50% of 500k
begin
  -- Check if donation
  if receiver_email = 'donate@rostara.ir' then -- Hardcoded Donation Address
    is_donation := true;
  end if;

  -- Get Sender Wallet
  select id, ticket_balance into v_sender_wallet_id, v_sender_tickets from public.wallets where user_id = auth.uid();
  
  if v_sender_tickets < 1 then raise exception 'You do not have any tickets'; end if;

  if not is_donation then
    -- Find Receiver User ID from Email (requires looking up auth.users? No, usually cannot query auth.users directly securely).
    -- Strategy: We need a mapping or we execute this as admin privilege function.
    -- For safety, we will assume we CAN look up public profiles if we had them. 
    -- Workaround: Lookup in 'public.orders' recent email? Unreliable.
    -- Best Practice: We need a 'public.profiles' table that exposes emails or rely on Admin to handle transfers.
    -- BUT for this demo, let's assume we can query auth.users because we are using 'security definer' function.
    select id into v_receiver_user_id from auth.users where email = receiver_email;
    if v_receiver_user_id is null then raise exception 'User not found'; end if;

    -- Get Receiver Wallet
    select id into v_receiver_wallet_id from public.wallets where user_id = v_receiver_user_id;
    if v_receiver_wallet_id is null then 
        -- Create wallet if missing (auto-heal)
        insert into public.wallets (user_id) values (v_receiver_user_id) returning id into v_receiver_wallet_id;
    end if;

    -- Update Receiver
    update public.wallets set ticket_balance = ticket_balance + 1 where id = v_receiver_wallet_id;
    
    -- Record Receiver Log
    insert into public.wallet_transactions (wallet_id, type, ticket_amount, description)
    values (v_receiver_wallet_id, 'transfer_in', 1, 'دریافت تیکت از ' || auth.jwt() ->> 'email');
  end if;

  -- Update Sender (Always deduct 1 ticket)
  update public.wallets 
  set ticket_balance = ticket_balance - 1
  where id = v_sender_wallet_id;

  -- Record Sender Log
  insert into public.wallet_transactions (wallet_id, type, ticket_amount, description)
  values (v_sender_wallet_id, 'transfer_out', -1, 'ارسال تیکت به ' || receiver_email);

  -- Handle Donation Reward
  if is_donation then
    update public.wallets 
    set credit_balance = credit_balance + v_donation_reward
    where id = v_sender_wallet_id;

    insert into public.wallet_transactions (wallet_id, type, amount, description)
    values (v_sender_wallet_id, 'donation_reward', v_donation_reward, 'پاداش ۵۰٪ دونیت تیکت');
  end if;

end;
$$ language plpgsql security definer;
-- VIP System Functions

-- 1. Click 'Vaqt Bekheir'
-- Logic: 
--  - Reset daily_clicks if last_click_date is not today.
--  - Increment daily_clicks.
--  - If daily_clicks reaches 29, increment vip_level (max 7).
--  - Return new status.

-- 1. Click 'Vaqt Bekheir'
-- Logic: 
--  - Check if 24 hours passed since last_click_at.
--  - Increment daily_clicks (treated as cycle clicks).
--  - If daily_clicks reaches 7:
--    - Increment vip_level (max 7).
--    - Reset daily_clicks to 0.

create or replace function click_vaqt_bekheir()
returns jsonb
language plpgsql
security definer
as $$
declare
  wallet_row public.wallets%rowtype;
  result jsonb;
  new_clicks int;
  new_level int;
  last_click timestamp with time zone;
  time_diff interval;
  can_click boolean;
  hours_until_next int;
begin
  select * into wallet_row from public.wallets where user_id = auth.uid();
  if not found then
    -- Auto-heal: Create wallet if missing
    insert into public.wallets (user_id) values (auth.uid()) returning * into wallet_row;
  end if;

  -- Handle column migration implicitly by casting if needed, or assume last_click_at exists
  -- For this script, we assume we are updating the logic.
  -- If last_click_date was used, we treat midnight as the time? 
  -- No, we will start fresh or assume null means clickable.
  
  -- Logic for cooldown
  if wallet_row.last_click_at is null then
    can_click := true;
  else
    time_diff := now() - wallet_row.last_click_at;
    if time_diff < interval '24 hours' then
       can_click := false;
       hours_until_next := 24 - extract(epoch from time_diff) / 3600;
    else
       can_click := true;
    end if;
  end if;

  if not can_click then
     return jsonb_build_object(
       'success', false,
       'message', 'Please wait ' || hours_until_next || ' hours',
       'daily_clicks', wallet_row.daily_clicks,
       'vip_level', wallet_row.vip_level,
       'next_click_at', wallet_row.last_click_at + interval '24 hours'
     );
  end if;

  -- Process Click
  new_clicks := wallet_row.daily_clicks + 1;
  new_level := wallet_row.vip_level;
  
  -- Level up logic: 7 clicks to level up
  if new_clicks >= 7 and new_level < 7 then
    new_level := new_level + 1;
    new_clicks := 0; -- Reset cycle
  end if;

  update public.wallets
  set 
    daily_clicks = new_clicks,
    last_click_at = now(), -- Update timestamp
    vip_level = new_level
  where id = wallet_row.id;

  result := jsonb_build_object(
    'success', true,
    'daily_clicks', new_clicks,
    'vip_level', new_level,
    'leveled_up', (new_level > wallet_row.vip_level),
    'next_click_at', now() + interval '24 hours'
  );

  return result;
end;
$$;


-- 2. Claim VIP Reward
-- Logic:
--  - Check if eligible (Level >= 3 for reward 1, Level >= 7 for reward 2).
--  - Check if already claimed.
--  - Add tickets.
--  - Update claimed_rewards.

create or replace function claim_vip_reward(reward_level int)
returns jsonb
language plpgsql
security definer
as $$
declare
  wallet_row public.wallets%rowtype;
  ticket_amount int;
begin
  select * into wallet_row from public.wallets where user_id = auth.uid();
  if not found then
      -- Auto-heal for claim reward too
      insert into public.wallets (user_id) values (auth.uid()) returning * into wallet_row;
  end if;
  
  if wallet_row.vip_level < reward_level then
    raise exception 'Level requirement not met';
  end if;

  if (wallet_row.claimed_rewards @> to_jsonb(reward_level)) then
    raise exception 'Reward already claimed';
  end if;

  -- Define rewards
  if reward_level = 3 then
    ticket_amount := 1;
  elsif reward_level = 7 then
    ticket_amount := 2;
  else
    raise exception 'Invalid reward level';
  end if;

  update public.wallets
  set 
    ticket_balance = ticket_balance + ticket_amount,
    claimed_rewards = claimed_rewards || to_jsonb(reward_level)
  where id = wallet_row.id;

  -- Log transaction
  insert into public.wallet_transactions (wallet_id, ticket_amount, description)
  values (wallet_row.id, ticket_amount, 'VIP Level ' || reward_level || ' Reward');

  return jsonb_build_object('success', true, 'tickets_added', ticket_amount);
end;
$$;

-- 5. Backfill Wallets for Existing Users
do $$
begin
  insert into public.wallets (user_id)
  select id from auth.users
  where id not in (select user_id from public.wallets);
end
$$;
