-- Create tables for the Forum Feature

-- 1. Forum Posts
create table if not exists public.forum_posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text not null,
  user_id uuid references auth.users not null,
  user_email text, -- Storing email for display (or use a profile table join)
  category text default 'general',
  likes_count int default 0,
  comments_count int default 0
);

-- 2. Forum Comments
create table if not exists public.forum_comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  post_id bigint references public.forum_posts not null,
  user_id uuid references auth.users not null,
  user_email text,
  content text not null
);

-- 3. Forum Likes
create table if not exists public.forum_likes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  post_id bigint references public.forum_posts not null,
  user_id uuid references auth.users not null,
  unique(post_id, user_id)
);

-- Enable RLS
alter table public.forum_posts enable row level security;
alter table public.forum_comments enable row level security;
alter table public.forum_likes enable row level security;

-- Policies

-- Public Read Access
create policy "Public posts are viewable by everyone" on public.forum_posts for select using (true);
create policy "Public comments are viewable by everyone" on public.forum_comments for select using (true);
create policy "Public likes are viewable by everyone" on public.forum_likes for select using (true);

-- Authenticated Create/Update/Delete

-- Posts: Only users with at least 1 order can create (Star Users)
-- Note: This requires the 'orders' table to exist and be linked to auth.users
create policy "Star users can create posts" on public.forum_posts for insert with check (
  auth.uid() in (select user_id from public.orders)
);

-- Comments: Any authenticated user can comment
create policy "Authenticated users can comment" on public.forum_comments for insert with check (
  auth.role() = 'authenticated'
);

-- Likes: Any authenticated user can like
create policy "Authenticated users can like" on public.forum_likes for insert with check (
  auth.role() = 'authenticated'
);

create policy "Users can dislike (delete like)" on public.forum_likes for delete using (
  auth.uid() = user_id
);
